tap "caskroom/cask"
tap "git-duet/tap"
tap "homebrew/bundle"
tap "homebrew/core"
tap "thoughtbot/formulae"
tap "universal-ctags/universal-ctags"
brew "vim"
brew "git-duet/tap/git-duet"
brew "thoughtbot/formulae/rcm"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "1password"
cask "google-chrome"
cask "spectacle"
