#!/usr/bin/env sh

_setup() {
  dotfiles_dir="$(cd "$(dirname "${0}")" && pwd)"

  . "${dotfiles_dir}/profile"

  if ! [ -x "$(command -v brew)" ]; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  else
    echo "Homebrew already installed"
  fi

  echo "Running 'brew bundle'"
  HOMEBREW_BUNDLE_FILE="${dotfiles_dir}/Brewfile" brew bundle

  echo "Running 'rcup'"
  RCRC="${dotfiles_dir}/rcrc" rcup -v
}

_setup

unset _setup

exec zsh -l

