#!/usr/bin/env sh
set -euo

_setup_gitconfig() {
  dotfiles_dir="$(cd "$(dirname "${0}")"; cd ..; pwd)"
  include_path="path=\"${dotfiles_dir}/git-include\""
  include_directive="[include]
  ${include_path}"

  gitconfig_file="${HOME}/.gitconfig"

  if ! grep --quiet "${include_path}" "${gitconfig_file}" 2> /dev/null; then
    echo "Appending to '${gitconfig_file}':"
    echo "${include_directive}"
    echo ""

    echo "" >> "${gitconfig_file}"
    echo "${include_directive}" >> "${gitconfig_file}"
  fi
}

_install_luan_nvim_config() {
  nvim_config_dir="${HOME}/.config/nvim"
  test -d "${nvim_config_dir}" || git clone https://github.com/luan/nvim "${nvim_config_dir}"
  pip3 install neovim
}

_fix_permissions_on_usr_local_share() {
  if [ "$(uname -p)" = 'arm' ]; then
    local brew_prefix='/opt/homebrew'
  else
    local brew_prefix='/usr/local'
  fi

  chmod 755 "${brew_prefix}/share"
}

main() {
  _setup_gitconfig
  _fix_permissions_on_usr_local_share
  _install_luan_nvim_config
}

main
